spring.application.name=net-pay-backend

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/netpay_db
spring.datasource.username=dtzunun_cunoc
spring.datasource.password=T@zi99k2
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway Settings
spring.flyway.enabled=true
spring.flyway.clean-disabled=true
spring.flyway.locations=classpath:db/migration

security.jwt.expiration=3600
security.jwt.secret=bWlfY2xhdmVfc2VjcmV0YV91bml2ZXJzaXRhcmlhX3BhcmFfbmV0cGF5XzIwMjZfMTIzNDU2Nzg5MA==
